repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key

  # Add Python compatibility checks for all supported versions
  - repo: local
    hooks:
      - id: python310-compat-check
        name: Python 3.10 Compatibility Check
        entry: pyenv exec python3.10 -m py_compile
        language: system
        types: [python]
        pass_filenames: true

      - id: python311-compat-check
        name: Python 3.11 Compatibility Check
        entry: pyenv exec python3.11 -m py_compile
        language: system
        types: [python]
        pass_filenames: true

      - id: python312-compat-check
        name: Python 3.12 Compatibility Check
        entry: pyenv exec python3.12 -m py_compile
        language: system
        types: [python]
        pass_filenames: true

      - id: python313-compat-check
        name: Python 3.13 Compatibility Check
        entry: pyenv exec python3.13 -m py_compile
        language: system
        types: [python]
        pass_filenames: true

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings, pyflakes]
        args: ["--config=.flake8", "--select=E9,F63,F7,F82,F401,F811,F841"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, pydantic]
        args: []
        exclude: ^(tests/|setup.py)

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
        exclude: ^(tests/|setup.py)

  # Run comprehensive tests with coverage requirements
  - repo: local
    hooks:
      - id: pytest-full
        name: Run comprehensive tests
        entry: poetry run pytest --cov=bluemastodon --cov-report=term-missing --cov-fail-under=100
        language: system
        pass_filenames: false
        always_run: true
        verbose: true

ci:
  autofix_commit_msg: "style: auto fixes from pre-commit hooks"
  autoupdate_commit_msg: "chore: update pre-commit hooks"
