# Pre-push hooks - these run before pushing to remote
repos:
  - repo: local
    hooks:
      # Run comprehensive tests
      - id: pytest-full
        name: Run comprehensive tests
        entry: poetry run pytest --cov=bluemastodon --cov-report=term-missing --cov-fail-under=100
        language: system
        pass_filenames: false
        always_run: true
        verbose: true

      # Run type checking
      - id: mypy-full
        name: Run full type checking
        entry: poetry run mypy src/bluemastodon
        language: system
        pass_filenames: false
        always_run: true
        verbose: true

      # Run comprehensive linting
      - id: lint-full
        name: Run comprehensive linting
        entry: |
          bash -c '
            poetry run black --check src/bluemastodon tests
            poetry run isort --check-only src/bluemastodon tests
            poetry run flake8 src/bluemastodon tests
            poetry run bandit -r src/bluemastodon
          '
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
